config:
  selfUrl: # https://saas.fandaq.dev
  corsOrigins: https://fandaq-st-gateway-web,https://fandaq-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://fandaq-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.fandaq.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: saas.fandaq.dev
  tlsSecret: fandaq-tls

image:
  repository: mycompanyname/fandaq-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      