config:
  selfUrl: # https://gateway-public.fandaq.dev
  corsOrigins: # https://fandaq-st-gateway-web,https://fandaq-st-gateway-public-web
  authServer:
    authority: # http://fandaq-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.fandaq.dev/.well-known/openid-configuration
    swaggerClientId: # WebGateway_Swagger
  dotnetEnv: Staging 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  AbpLicenseCode: #

reRoutes:
  accountService:
    url: http://fandaq-st-authserver
  saasService:
    url: http://saas-st-administration
  administrationService:
    url: http://fandaq-st-administration
  productService:
    url: http://fandaq-st-product

ingress:
  host: gateway-public.fandaq.dev
  tlsSecret: fandaq-tls

image:
  repository: mycompanyname/fandaq-gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    